### ISSUE TITLE
oci-security-health-check-standard output files has wrong path 

### ISSUE THREAD

**Issue by javierbm7** [oracle-devrel/technology-engineering#1214]
the output files has wrong path because the links in the file *standard_cis_html_summary_report.html has refered *_standard/cis_Identity_and_Access_Management_1-1.csv but the generated files not has the same path 

![image](https://github.com/user-attachments/assets/380ccc22-f014-4594-b4e6-4ce9831745d9)

![image](https://github.com/user-attachments/assets/3701cada-6de4-4395-8208-4842e31c171f)

**Comment by lvbirgelen** [comment]
Issue is resolved
