### ISSUE TITLE
Feedback on Networking ressources

### ISSUE THREAD

**Issue by AlexanderHodicke** [oracle-devrel/technology-engineering#153]

**Comment by AlexanderHodicke** [comment]
HA&DR Patterns in Network connectivity.pdf

Change the footer to 2023 and add 'Public' to the footer

**Comment by AlexanderHodicke** [comment]
Forwarding DNS requests to multiple On-Prem DNS Servers reference architecture.pdf

Change the footer to Public

**Comment by AlexanderHodicke** [comment]
Simple deploy guide of Private Dns integration with On-premises.pdf

Change the footer to 2023 and add 'Public'

**Comment by Vikramkurma** [comment]
HA&DR Patterns in Network connectivity.pdf - will fix footer after July 18th . Rest both were fixed and sent for review.
