### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by AlexanderHodicke** [oracle-devrel/technology-engineering#340]
'manageability-and-operations/observability-and-manageability/oci-monitoring/custom-metrics/custom-metric-python-SDK-services-limit-monitoring/files/Diagrams/custom-metrics-python-SDK-services-limit_solution1.png': Filename too long

Could you please rename your folders and file names, so the path is shortened? Thank you!

**Comment by paalonso** [comment]
Hi Alex!.

Sure, I'll rename and put you as reviewer.

Rgds.

Pablo

**Comment by AlexanderHodicke** [comment]
Approved, works! Thank you
